s1=str(input('nhap chuoi s1: '))
s2=str(input('nhap chuoi s2: '))
s3=str(input('nhap chuoi s3: '))
nhapindex=eval(input('nhap gia tri index: '))
print('chieu dai chuoi',len(s1))
print('chieu dai chuoi',len(s2))
print('chieu dai chuoi',len(s3))
print('chuoi s4',s1[2:5])
print('lap lai chuoi 2 lan',s2*2)